import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Sayed",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "Ali",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Apple MacBook Pro 16",
      slug: "apple-macBookpro16",
      category: "Laptop",
      image: "/images/appl1.jpg",
      price: 950,
      brand: "Apple",
      rating: 5,
      countInStock: 10,
      description: "A popular laptop",
    },
    {
      name: "Apple MacBook Pro 14",
      slug: "apple-macBookpro14",
      category: "Laptop",
      image: "/images/appl2.jpg",
      price: 800,
      brand: "Apple",
      rating: 4.5,
      countInStock: 15,
      description: "A popular laptop",
    },
    // {
    //   name: "Apple MacBook Air 13",
    //   slug: "apple-macBookair13",
    //   category: "Laptop",
    //   image: "/images/appl3.jpg",
    //   price: 750,
    //   brand: "Apple",
    //   rating: 4,
    //   countInStock: 20,
    //   description: "A popular laptop",
    // },
    {
      name: "Dell Xps",
      slug: "dell-xps",
      category: "Laptop",
      image: "/images/del1.jpg",
      price: 700,
      brand: "Dell",
      rating: 4,
      countInStock: 15,
      description: "A popular laptop",
    },
    {
      name: "Dell Latitude ",
      slug: "dell-latitude",
      category: "Laptop",
      image: "/images/del2.jpg",
      price: 450,
      brand: "Dell",
      rating: 4,
      countInStock: 20,
      description: "A popular laptop",
    },
    // {
    //   name: "Dell Vostro ",
    //   slug: "dell-vostro",
    //   category: "Laptop",
    //   image: "/images/del3.jpg",
    //   price: 400,
    //   brand: "Dell",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular laptop",
    // },
    // {
    //   name: "Hp Spectre ",
    //   slug: "hp-spectre",
    //   category: "Laptop",
    //   image: "/images/hp1.jpg",
    //   price: 650,
    //   brand: "Hp",
    //   rating: 4.5,
    //   countInStock: 15,
    //   description: "A popular laptop",
    // },
    // {
    //   name: "Hp ProBook ",
    //   slug: "hp-probook",
    //   category: "Laptop",
    //   image: "/images/hp2.jpg",
    //   price: 500,
    //   brand: "Hp",
    //   rating: 4,
    //   countInStock: 20,
    //   description: "A popular laptop",
    // },
    // {
    //   name: "Hp 15gw ",
    //   slug: "hp-15gw",
    //   category: "Laptop",
    //   image: "/images/hp3.jpg",
    //   price: 370,
    //   brand: "Hp",
    //   rating: 2,
    //   countInStock: 20,
    //   description: "A popular laptop",
    // },
    {
      name: "Lg 4k-75inch ",
      slug: "lg-4k75inch",
      category: "Television",
      image: "/images/lg1.jpg",
      price: 500,
      brand: "Lg",
      rating: 5,
      countInStock: 10,
      description: "A popular television",
    },
    {
      name: "Lg 4k-55inch ",
      slug: "lg-4k55inch",
      category: "Television",
      image: "/images/lg2.jpg",
      price: 400,
      brand: "Lg",
      rating: 4.5,
      countInStock: 15,
      description: "A popular television",
    },
    // {
    //   name: "Lg Uhd-43inch",
    //   slug: "lg-uhd43inch",
    //   category: "Television",
    //   image: "/images/lg3.jpg",
    //   price: 300,
    //   brand: "Lg",
    //   rating: 4,
    //   countInStock: 20,
    //   description: "A popular television",
    // },
    {
      name: "Sharp 4K-50inch ",
      slug: "sharp-4K50inch ",
      category: "Television",
      image: "/images/sha1.jpg",
      price: 420,
      brand: "Sharp",
      rating: 4,
      countInStock: 20,
      description: "A popular television",
    },
    {
      name: "Sharp Hd-43inch  ",
      slug: "sharp-hd43inch  ",
      category: "Television",
      image: "/images/sha2.jpg",
      price: 350,
      brand: "Sharp",
      rating: 3,
      countInStock: 20,
      description: "A popular television",
    },
    // {
    //   name: "Sharp Hd-32inch  ",
    //   slug: "sharp-hd32inch  ",
    //   category: "Television",
    //   image: "/images/sha3.jpg",
    //   price: 300,
    //   brand: "Sharp",
    //   rating: 2,
    //   countInStock: 20,
    //   description: "A popular television",
    // },
    // {
    //   name: "Toshiba 4k-75inch ",
    //   slug: "toshiba-4k75inch ",
    //   category: "Television",
    //   image: "/images/tosh1.jpg",
    //   price: 550,
    //   brand: "Toshiba",
    //   rating: 4,
    //   countInStock: 20,
    //   description: "A popular television",
    // },
    // {
    //   name: "Toshiba Hd-43inch ",
    //   slug: "toshiba-hd43inch ",
    //   category: "Television",
    //   image: "/images/tosh2.jpg",
    //   price: 550,
    //   brand: "Toshiba",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular television",
    // },
    // {
    //   name: "Toshiba Hd-32inch ",
    //   slug: "toshiba-hd32inch ",
    //   category: "Television",
    //   image: "/images/tosh3.jpg",
    //   price: 250,
    //   brand: "Toshiba",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular television",
    // },
    {
      name: "Huawei Nova9 SE ",
      slug: "huawei-nova9se ",
      category: "Mobile",
      image: "/images/hua1.jpg",
      price: 350,
      brand: "Huawei",
      rating: 4,
      countInStock: 15,
      description: "A popular mobile",
    },
    {
      name: "Huawei Nova9 Y70 ",
      slug: "huawei-nova9y70 ",
      category: "Mobile",
      image: "/images/hua2.jpg",
      price: 250,
      brand: "Huawei",
      rating: 3.5,
      countInStock: 20,
      description: "A popular mobile",
    },
    // {
    //   name: "Huawei Nova9 Y90 ",
    //   slug: "huawei-nova9y90 ",
    //   category: "Mobile",
    //   image: "/images/hua3.jpg",
    //   price: 200,
    //   brand: "Huawei",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular mobile",
    // },
    {
      name: "Oppo Reno7",
      slug: "oppo-reno7",
      category: "Mobile",
      image: "/images/opp1.jpg",
      price: 350,
      brand: "Oppo",
      rating: 4.5,
      countInStock: 10,
      description: "A popular mobile",
    },
    {
      name: "Oppo A16",
      slug: "oppo-a16",
      category: "Mobile",
      image: "/images/opp2.jpg",
      price: 175,
      brand: "Oppo",
      rating: 3,
      countInStock: 20,
      description: "A popular mobile",
    },
    // {
    //   name: "Oppo A96",
    //   slug: "oppo-a96",
    //   category: "Mobile",
    //   image: "/images/opp3.jpg",
    //   price: 200,
    //   brand: "Oppo",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular mobile",
    // },
    // {
    //   name: "Samsung Galaxy A52 ",
    //   slug: "samsung-galaxya52 ",
    //   category: "Mobile",
    //   image: "/images/sam1.jpg",
    //   price: 400,
    //   brand: "Samsung",
    //   rating: 4,
    //   countInStock: 20,
    //   description: "A popular mobile",
    // },
    // {
    //   name: "Samsung Galaxy A32 ",
    //   slug: "samsung-galaxya32 ",
    //   category: "Mobile",
    //   image: "/images/sam2.jpg",
    //   price: 300,
    //   brand: "Samsung",
    //   rating: 3,
    //   countInStock: 20,
    //   description: "A popular mobile",
    // },
    // {
    //   name: "Samsung Galaxy A13 ",
    //   slug: "samsung-galaxya13 ",
    //   category: "Mobile",
    //   image: "/images/sam3.jpg",
    //   price: 150,
    //   brand: "Samsung",
    //   rating: 2,
    //   countInStock: 20,
    //   description: "A popular mobile",
    // },
  ],
};

export default data;
